version: '3'

services:
  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_PORT: "app:8080"
      NGROK_AUTH: "${NGROK_AUTH}"
      NGROK_SUBDOMAIN: "${NGROK_SUBDOMAIN}"
      NGROK_REGION: "${NGROK_REGION}"
      NGROK_PROTOCOL: "http"
    restart: unless-stopped

  app:
    build:
      context: ./
      args:
        REACT_APP_WS_PATH: ${REACT_APP_WS_PATH}
    restart: unless-stopped

